kind: Service
apiVersion: v1
metadata:
  name: wordle-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: wordle
  type: LoadBalancer
